name: GhostVM
options:
  bundleIdPrefix: sh.fixie
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.4"

settings:
  base:
    SWIFT_VERSION: "6.0"
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES

targets:
  GhostVM:
    type: application
    platform: macOS
    sources:
      - path: GhostVM
        excludes:
          - "vmctl.swift"
          - "*.plist"
    settings:
      base:
        PRODUCT_NAME: GhostVM
        PRODUCT_BUNDLE_IDENTIFIER: sh.fixie.vm
        INFOPLIST_FILE: GhostVM/VMApp-Info.plist
        CODE_SIGN_ENTITLEMENTS: GhostVM/entitlements.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 3FGZQE8AW3
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: NO
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
