name: GhostVMSwiftUI
options:
  bundleIdPrefix: sh.fixie
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.4"

settings:
  base:
    SWIFT_VERSION: "6.0"
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES

targets:
  GhostVMSwiftUI:
    type: application
    platform: macOS
    sources:
      - path: SwiftUIDemoApp.swift
      - path: App2Models.swift
      - path: App2VMRuntime.swift
      - path: App2VMDisplayHost.swift
      - path: App2IPSW.swift
      - path: FinderAdapter.swift
      - path: SavePanelAdapter.swift
      - path: App2AppDelegate.swift
      - path: AppIconAdapter.swift
    settings:
      base:
        PRODUCT_NAME: GhostVMSwiftUI
        PRODUCT_BUNDLE_IDENTIFIER: sh.fixie.vm
        INFOPLIST_FILE: VMApp-Info.plist
        CODE_SIGN_ENTITLEMENTS: entitlements.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 3FGZQE8AW3
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: NO
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
