name: GhostVM
options:
  bundleIdPrefix: org.ghostvm
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.4"

packages:
  swift-nio:
    url: https://github.com/apple/swift-nio.git
    from: "2.65.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    from: "2.6.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES

targets:
  GhostVMKit:
    type: framework
    platform: macOS
    sources:
      - path: GhostVMKit
    settings:
      base:
        PRODUCT_NAME: GhostVMKit
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvmkit
        GENERATE_INFOPLIST_FILE: YES
        DEFINES_MODULE: YES
        SWIFT_VERSION: "5.0"
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
          - "@loader_path/../Frameworks"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        ENABLE_HARDENED_RUNTIME: YES

  vmctl:
    type: tool
    platform: macOS
    sources:
      - path: GhostVM/vmctl
        excludes:
          - "CEditLine"
    dependencies:
      - target: GhostVMKit
        link: true
        embed: false
    settings:
      base:
        PRODUCT_NAME: vmctl
        SWIFT_VERSION: "5.0"
        CODE_SIGN_ENTITLEMENTS: GhostVM/entitlements.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/GhostVM/vmctl/CEditLine"
        OTHER_LDFLAGS:
          - "-ledit"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "@executable_path"

  GhostVMHelper:
    type: application
    platform: macOS
    sources:
      - path: GhostVMHelper
      - path: GhostVM/Services
      - path: GhostVM/Resources/VMIcons
        type: resource
        buildPhase: resources
      - path: ../Resources
        type: resource
        buildPhase: resources
    dependencies:
      - target: GhostVMKit
        embed: true
      - package: swift-nio
        products:
          - NIOCore
          - NIOPosix
    settings:
      base:
        PRODUCT_NAME: GhostVMHelper
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvm.helper
        INFOPLIST_FILE: GhostVMHelper/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.0"
        CODE_SIGN_ENTITLEMENTS: GhostVMHelper/entitlements.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"

  GhostVM:
    type: application
    platform: macOS
    sources:
      - path: GhostVM
        excludes:
          - "vmctl"
          - "vmctl.swift"
          - "*.plist"
    resources:
      - path: build/xcode/GhostTools.dmg
        optional: true
    dependencies:
      - target: GhostVMKit
        embed: true
      - target: vmctl
        embed: true
        codeSign: true
        copy:
          destination: executables
      - target: GhostVMHelper
        embed: true
        codeSign: true
        copy:
          destination: plugins
          subpath: Helpers
      - package: swift-nio
        products:
          - NIOCore
          - NIOPosix
      - package: Sparkle
    settings:
      base:
        PRODUCT_NAME: GhostVM
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvm
        INFOPLIST_FILE: GhostVM/VMApp-Info.plist
        CODE_SIGN_ENTITLEMENTS: GhostVM/entitlements.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: NO
        SWIFT_VERSION: "5.0"
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES

  GhostVMTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: GhostVMTests
    dependencies:
      - target: GhostVMKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvm.tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"

  GhostVMUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: GhostVMUITests
    dependencies:
      - target: GhostVM
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvm.uitests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
        ENABLE_APP_SANDBOX: NO

  GhostVMHelperUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: GhostVMHelperUITests
    dependencies:
      - target: GhostVMHelper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.ghostvm.ghostvm.helper.uitests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
        ENABLE_APP_SANDBOX: NO
